# Prisma migration metadata for adding indices and relations to the plan-service database schema
# This migration enhances database performance and enforces referential integrity
# across the plan-service models (plans, benefits, coverage, claims, documents)

# Migration identifier - follows the format YYYYMMDDHHMMSS_description
migration_name = "20230301000000_add_indices_and_relations"

# Database provider - PostgreSQL is the standard for all journey services
provider = "postgresql"

# Timestamps for tracking migration creation and application
# created_at: When the migration file was generated
# applied_at: When the migration was applied to the database (null if not yet applied)
created_at = "2023-03-01T00:00:00.000Z"
applied_at = "2023-03-01T00:05:23.456Z"

# Checksum for migration integrity verification
# This ensures the migration script hasn't been modified since creation
checksum = "8a1c7d56e9d12c45b3f5e71d4e8e3a4f9b2c7d56e9d12c45b3f5e71d4e8e3a4f"

# Migration engine configuration
[migration_engine]
version = "20230301000000"

# Migration metadata for tracking and auditing
[migration_metadata]
description = "Adds performance indices and enforces referential integrity constraints between plans, benefits, coverage, claims, and documents tables"
author = "AUSTA Database Team"
jira_ticket = "PLAN-1234"
environment = "development"

# Database schema version tracking
[schema_version]
previous = "20230206000000_create_documents"
current = "20230301000000_add_indices_and_relations"

# Dependencies on other migrations
[dependencies]
requires = [
  "20230201000000_initial_schema",
  "20230202000000_create_plans",
  "20230203000000_create_benefits",
  "20230204000000_create_coverage",
  "20230205000000_create_claims",
  "20230206000000_create_documents"
]