apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: health-journey
  namespace: health-journey
  labels:
    app: health-journey
    journey: health
    part-of: austa-superapp
    managed-by: terraform
  annotations:
    description: "Horizontal Pod Autoscaler for Health Journey service"
    last-updated: "2023-04-15"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-journey
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60