version: 2
updates:
  # Backend root pnpm dependencies
  - package-ecosystem: "pnpm"
    directory: "/src/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "rodaquino-OMNI"
    labels:
      - "dependencies"
      - "backend"
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "eslint*"
          - "prettier*"
          - "test*"
          - "jest*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint*"
      - dependency-name: "prettier*"
      - dependency-name: "typescript"
        update-types: ["version-update:semver-minor"]
    commit-message:
      prefix: "deps"
      include: "scope"
        
  # Gamification Engine pnpm dependencies
  - package-ecosystem: "pnpm"
    directory: "/src/backend/gamification-engine"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "rodaquino-OMNI"
    labels:
      - "dependencies"
      - "gamification"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint*"
      - dependency-name: "prettier*"
    commit-message:
      prefix: "deps"
      include: "scope"
        
  # API Gateway pnpm dependencies
  - package-ecosystem: "pnpm"
    directory: "/src/backend/api-gateway"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "rodaquino-OMNI"
    labels:
      - "dependencies"
      - "api-gateway"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint*"
      - dependency-name: "prettier*"
    commit-message:
      prefix: "deps"
      include: "scope"
        
  # Web root pnpm dependencies
  - package-ecosystem: "pnpm"
    directory: "/src/web"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "rodaquino-OMNI"
    labels:
      - "dependencies"
      - "frontend"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint*"
      - dependency-name: "prettier*"
      - dependency-name: "@types/*"
        update-types: ["version-update:semver-minor"]
    commit-message:
      prefix: "deps"
      include: "scope"

  # Design System Primitives pnpm dependencies
  - package-ecosystem: "pnpm"
    directory: "/src/web/primitives"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "rodaquino-OMNI"
    labels:
      - "dependencies"
      - "design-system"
      - "primitives"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint*"
      - dependency-name: "prettier*"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Interfaces pnpm dependencies
  - package-ecosystem: "pnpm"
    directory: "/src/web/interfaces"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "rodaquino-OMNI"
    labels:
      - "dependencies"
      - "interfaces"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint*"
      - dependency-name: "prettier*"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Journey Context pnpm dependencies
  - package-ecosystem: "pnpm"
    directory: "/src/web/journey-context"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "rodaquino-OMNI"
    labels:
      - "dependencies"
      - "journey-context"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint*"
      - dependency-name: "prettier*"
    commit-message:
      prefix: "deps"
      include: "scope"
        
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "rodaquino-OMNI"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
      include: "scope"
      
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/src/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "rodaquino-OMNI"
    labels:
      - "dependencies"
      - "docker"
    groups:
      docker-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "docker"
      include: "scope"
      
  # Vulnerability alerts for all ecosystems
  - package-ecosystem: "pnpm"
    directory: "/src/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "security"
    target-branch: "main"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]