# AUSTA SuperApp Yarn Configuration
# Standardized package manager configuration for monorepo

# Use node_modules mode for consistent dependency resolution
nodeLinker: node-modules

# Use official npm registry
npmRegistryServer: "https://registry.yarnpkg.com"

# Update checksums when needed
checksumBehavior: update

# Explicitly set Yarn version for consistency
yarnPath: ".yarn/releases/yarn-1.22.19.cjs"

# Enable workspace-aware dependency resolution
enableGlobalCache: false
workspaceFocus: true

# Configure package extensions to fix dependency conflicts
packageExtensions:
  # Fix React Native dependencies
  "react-native@*":
    dependencies:
      "@babel/core": "^7.20.0"
      "@babel/preset-env": "^7.20.0"
      "@types/react": "^18.2.0"
  
  # Fix Agora SDK dependencies
  "agora-rtc-sdk@*":
    dependencies:
      "follow-redirects": "1.15.4"
      "axios": "1.6.8"
  "agora-rtc-sdk-ng@*":
    dependencies:
      "follow-redirects": "1.15.4"
      "axios": "1.6.8"
  
  # Fix Sentry dependencies
  "@sentry/nextjs@*":
    dependencies:
      "@babel/traverse": "7.23.2"
      "webpack": "5.76.0"
  
  # Fix React ecosystem dependencies
  "react@*":
    peerDependencies:
      "react-dom": "*"
  "react-dom@*":
    peerDependencies:
      "react": "*"
  "@emotion/react@*":
    peerDependencies:
      "@types/react": "*"

# Resolutions for version conflicts
resolutions:
  # Core dependencies with version conflicts
  "minimatch": "3.1.2"
  "semver": "7.5.4"
  "ws": "8.16.0"
  
  # React ecosystem
  "react": "18.2.0"
  "react-dom": "18.2.0"
  "react-native": "0.73.4"
  
  # AUSTA internal packages
  "@austa/design-system": "1.0.0"
  "@design-system/primitives": "1.0.0"
  "@austa/interfaces": "1.0.0"
  "@austa/journey-context": "1.0.0"

# Prevent hoisting of certain packages that need to stay in their own node_modules
nohoist:
  - "**/react-native"
  - "**/react-native/**"
  - "**/@react-native-community/**"
  - "**/expo"
  - "**/expo/**"