/**
 * Appointment interface for the AUSTA SuperApp Care journey.
 * Represents scheduled healthcare appointments with comprehensive tracking of status,
 * timing, provider information, and associated notes.
 */

import { AppointmentType, AppointmentStatus } from './types';

/**
 * Represents a healthcare appointment in the Care journey.
 * Used for scheduling, displaying, and managing appointments across the application.
 */
export interface Appointment {
  /**
   * Unique identifier for the appointment.
   * Generated by the backend when appointment is created.
   */
  id: string;

  /**
   * User ID of the patient who scheduled the appointment.
   * Links the appointment to a specific user account.
   */
  userId: string;

  /**
   * Type of appointment (in-person or virtual).
   * Determines the appointment workflow and required information.
   */
  type: AppointmentType;

  /**
   * Current status of the appointment.
   * Updated throughout the appointment lifecycle.
   */
  status: AppointmentStatus;

  /**
   * Scheduled start date and time of the appointment.
   * Stored in ISO format with timezone information.
   */
  scheduledAt: string;

  /**
   * Estimated duration of the appointment in minutes.
   * Used for scheduling and calendar display.
   */
  durationMinutes: number;

  /**
   * ID of the healthcare provider for this appointment.
   * References a provider in the system.
   */
  providerId: string;

  /**
   * Name of the healthcare provider.
   * Stored directly for display purposes without requiring provider lookup.
   */
  providerName: string;

  /**
   * Provider's specialty or department.
   * Helps categorize the appointment type.
   */
  providerSpecialty: string;

  /**
   * Physical location where the appointment will take place.
   * Required for IN_PERSON appointments, optional for VIRTUAL.
   */
  location?: {
    /**
     * Name of the facility or clinic.
     */
    name: string;
    
    /**
     * Street address of the facility.
     */
    address: string;
    
    /**
     * City of the facility location.
     */
    city: string;
    
    /**
     * State or province of the facility location.
     */
    state: string;
    
    /**
     * Postal code of the facility location.
     */
    zipCode: string;
    
    /**
     * Optional additional instructions for finding the location.
     */
    instructions?: string;
  };

  /**
   * For virtual appointments, contains connection details.
   * Required for VIRTUAL appointments, not present for IN_PERSON.
   */
  virtualMeeting?: {
    /**
     * URL for joining the virtual appointment.
     */
    joinUrl: string;
    
    /**
     * Meeting ID for the virtual appointment.
     */
    meetingId: string;
    
    /**
     * Optional password for joining the meeting.
     */
    password?: string;
    
    /**
     * Provider of the virtual meeting service (e.g., Zoom, Teams).
     */
    provider: string;
  };

  /**
   * Reason or purpose for the appointment.
   * Entered during scheduling process.
   */
  reason: string;

  /**
   * Additional notes about the appointment.
   * Can be updated by both patient and provider.
   */
  notes?: string;

  /**
   * Instructions for the patient to prepare for the appointment.
   * Set by the provider or clinic.
   */
  instructions?: string;

  /**
   * Timestamp when the appointment was created.
   * Stored in ISO format.
   */
  createdAt: string;

  /**
   * Timestamp when the appointment was last updated.
   * Stored in ISO format.
   */
  updatedAt: string;

  /**
   * If appointment is cancelled, stores the reason for cancellation.
   * Required when status is CANCELLED.
   */
  cancellationReason?: string;

  /**
   * Indicates whether the appointment is eligible for rescheduling.
   * Based on provider availability and clinic policies.
   */
  canReschedule: boolean;

  /**
   * For completed appointments, contains follow-up information.
   * Only present when status is COMPLETED.
   */
  followUp?: {
    /**
     * Instructions for follow-up care.
     */
    instructions: string;
    
    /**
     * Recommended date for follow-up appointment.
     * Stored in ISO format.
     */
    recommendedDate?: string;
    
    /**
     * Whether a follow-up appointment is required.
     */
    required: boolean;
  };
}