/**
 * Error codes for the Plan journey.
 * 
 * This file defines all error codes used throughout the Plan journey, organized by domain
 * (plans, benefits, coverage, claims, documents) and error type (validation, business,
 * technical, external). These codes provide a consistent error identification system that
 * enables precise error tracking, documentation, and localization.
 * 
 * Error code format: PLAN_[DOMAIN]_[TYPE]_[SPECIFIC_ERROR]
 * 
 * Domains:
 * - PLAN: Plan management
 * - BENEFIT: Benefits management
 * - COVERAGE: Coverage details
 * - CLAIM: Claims processing
 * - DOCUMENT: Document management
 * 
 * Types:
 * - VAL: Validation errors (input data fails validation)
 * - BUS: Business logic errors (operation cannot be completed due to business rules)
 * - TECH: Technical errors (unexpected system errors)
 * - EXT: External system errors (failures in external services)
 */

/**
 * Plan domain error codes
 * Related to insurance plan management, selection, and comparison
 */
export enum PlanErrorCodes {
  // Validation errors
  PLAN_PLAN_VAL_INVALID_ID = 'PLAN_PLAN_VAL_INVALID_ID',
  PLAN_PLAN_VAL_INVALID_NAME = 'PLAN_PLAN_VAL_INVALID_NAME',
  PLAN_PLAN_VAL_INVALID_DETAILS = 'PLAN_PLAN_VAL_INVALID_DETAILS',
  PLAN_PLAN_VAL_INVALID_PREMIUM = 'PLAN_PLAN_VAL_INVALID_PREMIUM',
  PLAN_PLAN_VAL_INVALID_DEDUCTIBLE = 'PLAN_PLAN_VAL_INVALID_DEDUCTIBLE',
  PLAN_PLAN_VAL_INVALID_COPAY = 'PLAN_PLAN_VAL_INVALID_COPAY',
  PLAN_PLAN_VAL_INVALID_COINSURANCE = 'PLAN_PLAN_VAL_INVALID_COINSURANCE',
  PLAN_PLAN_VAL_INVALID_NETWORK = 'PLAN_PLAN_VAL_INVALID_NETWORK',
  PLAN_PLAN_VAL_INVALID_CATEGORY = 'PLAN_PLAN_VAL_INVALID_CATEGORY',
  PLAN_PLAN_VAL_INVALID_PERIOD = 'PLAN_PLAN_VAL_INVALID_PERIOD',
  
  // Business logic errors
  PLAN_PLAN_BUS_NOT_FOUND = 'PLAN_PLAN_BUS_NOT_FOUND',
  PLAN_PLAN_BUS_ALREADY_EXISTS = 'PLAN_PLAN_BUS_ALREADY_EXISTS',
  PLAN_PLAN_BUS_NOT_ACTIVE = 'PLAN_PLAN_BUS_NOT_ACTIVE',
  PLAN_PLAN_BUS_NOT_ELIGIBLE = 'PLAN_PLAN_BUS_NOT_ELIGIBLE',
  PLAN_PLAN_BUS_ENROLLMENT_CLOSED = 'PLAN_PLAN_BUS_ENROLLMENT_CLOSED',
  PLAN_PLAN_BUS_INCOMPATIBLE_OPTION = 'PLAN_PLAN_BUS_INCOMPATIBLE_OPTION',
  PLAN_PLAN_BUS_REQUIRES_APPROVAL = 'PLAN_PLAN_BUS_REQUIRES_APPROVAL',
  PLAN_PLAN_BUS_EXCEEDS_LIMIT = 'PLAN_PLAN_BUS_EXCEEDS_LIMIT',
  
  // Technical errors
  PLAN_PLAN_TECH_PERSISTENCE_FAILURE = 'PLAN_PLAN_TECH_PERSISTENCE_FAILURE',
  PLAN_PLAN_TECH_RETRIEVAL_FAILURE = 'PLAN_PLAN_TECH_RETRIEVAL_FAILURE',
  PLAN_PLAN_TECH_UPDATE_FAILURE = 'PLAN_PLAN_TECH_UPDATE_FAILURE',
  PLAN_PLAN_TECH_DELETION_FAILURE = 'PLAN_PLAN_TECH_DELETION_FAILURE',
  PLAN_PLAN_TECH_TRANSACTION_FAILURE = 'PLAN_PLAN_TECH_TRANSACTION_FAILURE',
  
  // External system errors
  PLAN_PLAN_EXT_PROVIDER_UNAVAILABLE = 'PLAN_PLAN_EXT_PROVIDER_UNAVAILABLE',
  PLAN_PLAN_EXT_CATALOG_SYNC_FAILURE = 'PLAN_PLAN_EXT_CATALOG_SYNC_FAILURE',
  PLAN_PLAN_EXT_PRICING_SERVICE_FAILURE = 'PLAN_PLAN_EXT_PRICING_SERVICE_FAILURE',
  PLAN_PLAN_EXT_ELIGIBILITY_SERVICE_FAILURE = 'PLAN_PLAN_EXT_ELIGIBILITY_SERVICE_FAILURE',
  PLAN_PLAN_EXT_NETWORK_SERVICE_FAILURE = 'PLAN_PLAN_EXT_NETWORK_SERVICE_FAILURE'
}

/**
 * Benefit domain error codes
 * Related to plan benefits, coverage details, and benefit utilization
 */
export enum BenefitErrorCodes {
  // Validation errors
  PLAN_BENEFIT_VAL_INVALID_ID = 'PLAN_BENEFIT_VAL_INVALID_ID',
  PLAN_BENEFIT_VAL_INVALID_NAME = 'PLAN_BENEFIT_VAL_INVALID_NAME',
  PLAN_BENEFIT_VAL_INVALID_DESCRIPTION = 'PLAN_BENEFIT_VAL_INVALID_DESCRIPTION',
  PLAN_BENEFIT_VAL_INVALID_CATEGORY = 'PLAN_BENEFIT_VAL_INVALID_CATEGORY',
  PLAN_BENEFIT_VAL_INVALID_LIMIT = 'PLAN_BENEFIT_VAL_INVALID_LIMIT',
  PLAN_BENEFIT_VAL_INVALID_COVERAGE = 'PLAN_BENEFIT_VAL_INVALID_COVERAGE',
  PLAN_BENEFIT_VAL_INVALID_REQUIREMENT = 'PLAN_BENEFIT_VAL_INVALID_REQUIREMENT',
  
  // Business logic errors
  PLAN_BENEFIT_BUS_NOT_FOUND = 'PLAN_BENEFIT_BUS_NOT_FOUND',
  PLAN_BENEFIT_BUS_ALREADY_EXISTS = 'PLAN_BENEFIT_BUS_ALREADY_EXISTS',
  PLAN_BENEFIT_BUS_NOT_ACTIVE = 'PLAN_BENEFIT_BUS_NOT_ACTIVE',
  PLAN_BENEFIT_BUS_NOT_COVERED = 'PLAN_BENEFIT_BUS_NOT_COVERED',
  PLAN_BENEFIT_BUS_LIMIT_EXCEEDED = 'PLAN_BENEFIT_BUS_LIMIT_EXCEEDED',
  PLAN_BENEFIT_BUS_REQUIRES_PREAUTHORIZATION = 'PLAN_BENEFIT_BUS_REQUIRES_PREAUTHORIZATION',
  PLAN_BENEFIT_BUS_REQUIRES_REFERRAL = 'PLAN_BENEFIT_BUS_REQUIRES_REFERRAL',
  PLAN_BENEFIT_BUS_WAITING_PERIOD = 'PLAN_BENEFIT_BUS_WAITING_PERIOD',
  
  // Technical errors
  PLAN_BENEFIT_TECH_PERSISTENCE_FAILURE = 'PLAN_BENEFIT_TECH_PERSISTENCE_FAILURE',
  PLAN_BENEFIT_TECH_RETRIEVAL_FAILURE = 'PLAN_BENEFIT_TECH_RETRIEVAL_FAILURE',
  PLAN_BENEFIT_TECH_UPDATE_FAILURE = 'PLAN_BENEFIT_TECH_UPDATE_FAILURE',
  PLAN_BENEFIT_TECH_CALCULATION_FAILURE = 'PLAN_BENEFIT_TECH_CALCULATION_FAILURE',
  
  // External system errors
  PLAN_BENEFIT_EXT_PROVIDER_UNAVAILABLE = 'PLAN_BENEFIT_EXT_PROVIDER_UNAVAILABLE',
  PLAN_BENEFIT_EXT_CATALOG_SYNC_FAILURE = 'PLAN_BENEFIT_EXT_CATALOG_SYNC_FAILURE',
  PLAN_BENEFIT_EXT_UTILIZATION_SERVICE_FAILURE = 'PLAN_BENEFIT_EXT_UTILIZATION_SERVICE_FAILURE',
  PLAN_BENEFIT_EXT_AUTHORIZATION_SERVICE_FAILURE = 'PLAN_BENEFIT_EXT_AUTHORIZATION_SERVICE_FAILURE'
}

/**
 * Coverage domain error codes
 * Related to coverage details, eligibility, and network providers
 */
export enum CoverageErrorCodes {
  // Validation errors
  PLAN_COVERAGE_VAL_INVALID_ID = 'PLAN_COVERAGE_VAL_INVALID_ID',
  PLAN_COVERAGE_VAL_INVALID_MEMBER_ID = 'PLAN_COVERAGE_VAL_INVALID_MEMBER_ID',
  PLAN_COVERAGE_VAL_INVALID_PLAN_ID = 'PLAN_COVERAGE_VAL_INVALID_PLAN_ID',
  PLAN_COVERAGE_VAL_INVALID_EFFECTIVE_DATE = 'PLAN_COVERAGE_VAL_INVALID_EFFECTIVE_DATE',
  PLAN_COVERAGE_VAL_INVALID_TERMINATION_DATE = 'PLAN_COVERAGE_VAL_INVALID_TERMINATION_DATE',
  PLAN_COVERAGE_VAL_INVALID_STATUS = 'PLAN_COVERAGE_VAL_INVALID_STATUS',
  PLAN_COVERAGE_VAL_INVALID_NETWORK = 'PLAN_COVERAGE_VAL_INVALID_NETWORK',
  
  // Business logic errors
  PLAN_COVERAGE_BUS_NOT_FOUND = 'PLAN_COVERAGE_BUS_NOT_FOUND',
  PLAN_COVERAGE_BUS_ALREADY_EXISTS = 'PLAN_COVERAGE_BUS_ALREADY_EXISTS',
  PLAN_COVERAGE_BUS_INACTIVE = 'PLAN_COVERAGE_BUS_INACTIVE',
  PLAN_COVERAGE_BUS_EXPIRED = 'PLAN_COVERAGE_BUS_EXPIRED',
  PLAN_COVERAGE_BUS_FUTURE_DATED = 'PLAN_COVERAGE_BUS_FUTURE_DATED',
  PLAN_COVERAGE_BUS_OUT_OF_NETWORK = 'PLAN_COVERAGE_BUS_OUT_OF_NETWORK',
  PLAN_COVERAGE_BUS_PROVIDER_NOT_COVERED = 'PLAN_COVERAGE_BUS_PROVIDER_NOT_COVERED',
  PLAN_COVERAGE_BUS_SERVICE_NOT_COVERED = 'PLAN_COVERAGE_BUS_SERVICE_NOT_COVERED',
  
  // Technical errors
  PLAN_COVERAGE_TECH_PERSISTENCE_FAILURE = 'PLAN_COVERAGE_TECH_PERSISTENCE_FAILURE',
  PLAN_COVERAGE_TECH_RETRIEVAL_FAILURE = 'PLAN_COVERAGE_TECH_RETRIEVAL_FAILURE',
  PLAN_COVERAGE_TECH_UPDATE_FAILURE = 'PLAN_COVERAGE_TECH_UPDATE_FAILURE',
  PLAN_COVERAGE_TECH_ELIGIBILITY_CHECK_FAILURE = 'PLAN_COVERAGE_TECH_ELIGIBILITY_CHECK_FAILURE',
  
  // External system errors
  PLAN_COVERAGE_EXT_PROVIDER_UNAVAILABLE = 'PLAN_COVERAGE_EXT_PROVIDER_UNAVAILABLE',
  PLAN_COVERAGE_EXT_ELIGIBILITY_SERVICE_FAILURE = 'PLAN_COVERAGE_EXT_ELIGIBILITY_SERVICE_FAILURE',
  PLAN_COVERAGE_EXT_NETWORK_SERVICE_FAILURE = 'PLAN_COVERAGE_EXT_NETWORK_SERVICE_FAILURE',
  PLAN_COVERAGE_EXT_MEMBER_SERVICE_FAILURE = 'PLAN_COVERAGE_EXT_MEMBER_SERVICE_FAILURE'
}

/**
 * Claim domain error codes
 * Related to claim submission, processing, and payment
 */
export enum ClaimErrorCodes {
  // Validation errors
  PLAN_CLAIM_VAL_INVALID_ID = 'PLAN_CLAIM_VAL_INVALID_ID',
  PLAN_CLAIM_VAL_INVALID_MEMBER_ID = 'PLAN_CLAIM_VAL_INVALID_MEMBER_ID',
  PLAN_CLAIM_VAL_INVALID_PROVIDER_ID = 'PLAN_CLAIM_VAL_INVALID_PROVIDER_ID',
  PLAN_CLAIM_VAL_INVALID_SERVICE_DATE = 'PLAN_CLAIM_VAL_INVALID_SERVICE_DATE',
  PLAN_CLAIM_VAL_INVALID_DIAGNOSIS_CODE = 'PLAN_CLAIM_VAL_INVALID_DIAGNOSIS_CODE',
  PLAN_CLAIM_VAL_INVALID_PROCEDURE_CODE = 'PLAN_CLAIM_VAL_INVALID_PROCEDURE_CODE',
  PLAN_CLAIM_VAL_INVALID_AMOUNT = 'PLAN_CLAIM_VAL_INVALID_AMOUNT',
  PLAN_CLAIM_VAL_INVALID_DOCUMENT = 'PLAN_CLAIM_VAL_INVALID_DOCUMENT',
  PLAN_CLAIM_VAL_INVALID_STATUS = 'PLAN_CLAIM_VAL_INVALID_STATUS',
  PLAN_CLAIM_VAL_MISSING_REQUIRED_FIELD = 'PLAN_CLAIM_VAL_MISSING_REQUIRED_FIELD',
  
  // Business logic errors
  PLAN_CLAIM_BUS_NOT_FOUND = 'PLAN_CLAIM_BUS_NOT_FOUND',
  PLAN_CLAIM_BUS_ALREADY_EXISTS = 'PLAN_CLAIM_BUS_ALREADY_EXISTS',
  PLAN_CLAIM_BUS_DUPLICATE_SUBMISSION = 'PLAN_CLAIM_BUS_DUPLICATE_SUBMISSION',
  PLAN_CLAIM_BUS_EXPIRED_SUBMISSION = 'PLAN_CLAIM_BUS_EXPIRED_SUBMISSION',
  PLAN_CLAIM_BUS_INVALID_STATUS_TRANSITION = 'PLAN_CLAIM_BUS_INVALID_STATUS_TRANSITION',
  PLAN_CLAIM_BUS_DENIED = 'PLAN_CLAIM_BUS_DENIED',
  PLAN_CLAIM_BUS_REQUIRES_ADDITIONAL_INFO = 'PLAN_CLAIM_BUS_REQUIRES_ADDITIONAL_INFO',
  PLAN_CLAIM_BUS_NO_COVERAGE = 'PLAN_CLAIM_BUS_NO_COVERAGE',
  PLAN_CLAIM_BUS_SERVICE_NOT_COVERED = 'PLAN_CLAIM_BUS_SERVICE_NOT_COVERED',
  PLAN_CLAIM_BUS_EXCEEDS_BENEFIT_LIMIT = 'PLAN_CLAIM_BUS_EXCEEDS_BENEFIT_LIMIT',
  PLAN_CLAIM_BUS_MISSING_PREAUTHORIZATION = 'PLAN_CLAIM_BUS_MISSING_PREAUTHORIZATION',
  
  // Technical errors
  PLAN_CLAIM_TECH_PERSISTENCE_FAILURE = 'PLAN_CLAIM_TECH_PERSISTENCE_FAILURE',
  PLAN_CLAIM_TECH_RETRIEVAL_FAILURE = 'PLAN_CLAIM_TECH_RETRIEVAL_FAILURE',
  PLAN_CLAIM_TECH_UPDATE_FAILURE = 'PLAN_CLAIM_TECH_UPDATE_FAILURE',
  PLAN_CLAIM_TECH_PROCESSING_FAILURE = 'PLAN_CLAIM_TECH_PROCESSING_FAILURE',
  PLAN_CLAIM_TECH_CALCULATION_FAILURE = 'PLAN_CLAIM_TECH_CALCULATION_FAILURE',
  PLAN_CLAIM_TECH_TRANSACTION_FAILURE = 'PLAN_CLAIM_TECH_TRANSACTION_FAILURE',
  
  // External system errors
  PLAN_CLAIM_EXT_PROVIDER_UNAVAILABLE = 'PLAN_CLAIM_EXT_PROVIDER_UNAVAILABLE',
  PLAN_CLAIM_EXT_SUBMISSION_FAILURE = 'PLAN_CLAIM_EXT_SUBMISSION_FAILURE',
  PLAN_CLAIM_EXT_ADJUDICATION_FAILURE = 'PLAN_CLAIM_EXT_ADJUDICATION_FAILURE',
  PLAN_CLAIM_EXT_PAYMENT_PROCESSING_FAILURE = 'PLAN_CLAIM_EXT_PAYMENT_PROCESSING_FAILURE',
  PLAN_CLAIM_EXT_ELIGIBILITY_SERVICE_FAILURE = 'PLAN_CLAIM_EXT_ELIGIBILITY_SERVICE_FAILURE',
  PLAN_CLAIM_EXT_PROVIDER_DIRECTORY_FAILURE = 'PLAN_CLAIM_EXT_PROVIDER_DIRECTORY_FAILURE'
}

/**
 * Document domain error codes
 * Related to insurance documents, forms, and attachments
 */
export enum DocumentErrorCodes {
  // Validation errors
  PLAN_DOCUMENT_VAL_INVALID_ID = 'PLAN_DOCUMENT_VAL_INVALID_ID',
  PLAN_DOCUMENT_VAL_INVALID_TYPE = 'PLAN_DOCUMENT_VAL_INVALID_TYPE',
  PLAN_DOCUMENT_VAL_INVALID_FORMAT = 'PLAN_DOCUMENT_VAL_INVALID_FORMAT',
  PLAN_DOCUMENT_VAL_INVALID_SIZE = 'PLAN_DOCUMENT_VAL_INVALID_SIZE',
  PLAN_DOCUMENT_VAL_INVALID_CONTENT = 'PLAN_DOCUMENT_VAL_INVALID_CONTENT',
  PLAN_DOCUMENT_VAL_INVALID_METADATA = 'PLAN_DOCUMENT_VAL_INVALID_METADATA',
  PLAN_DOCUMENT_VAL_INVALID_OWNER = 'PLAN_DOCUMENT_VAL_INVALID_OWNER',
  
  // Business logic errors
  PLAN_DOCUMENT_BUS_NOT_FOUND = 'PLAN_DOCUMENT_BUS_NOT_FOUND',
  PLAN_DOCUMENT_BUS_ALREADY_EXISTS = 'PLAN_DOCUMENT_BUS_ALREADY_EXISTS',
  PLAN_DOCUMENT_BUS_ACCESS_DENIED = 'PLAN_DOCUMENT_BUS_ACCESS_DENIED',
  PLAN_DOCUMENT_BUS_EXPIRED = 'PLAN_DOCUMENT_BUS_EXPIRED',
  PLAN_DOCUMENT_BUS_LOCKED = 'PLAN_DOCUMENT_BUS_LOCKED',
  PLAN_DOCUMENT_BUS_QUOTA_EXCEEDED = 'PLAN_DOCUMENT_BUS_QUOTA_EXCEEDED',
  PLAN_DOCUMENT_BUS_REQUIRED_FOR_CLAIM = 'PLAN_DOCUMENT_BUS_REQUIRED_FOR_CLAIM',
  
  // Technical errors
  PLAN_DOCUMENT_TECH_PERSISTENCE_FAILURE = 'PLAN_DOCUMENT_TECH_PERSISTENCE_FAILURE',
  PLAN_DOCUMENT_TECH_RETRIEVAL_FAILURE = 'PLAN_DOCUMENT_TECH_RETRIEVAL_FAILURE',
  PLAN_DOCUMENT_TECH_UPDATE_FAILURE = 'PLAN_DOCUMENT_TECH_UPDATE_FAILURE',
  PLAN_DOCUMENT_TECH_DELETION_FAILURE = 'PLAN_DOCUMENT_TECH_DELETION_FAILURE',
  PLAN_DOCUMENT_TECH_STORAGE_FAILURE = 'PLAN_DOCUMENT_TECH_STORAGE_FAILURE',
  PLAN_DOCUMENT_TECH_PROCESSING_FAILURE = 'PLAN_DOCUMENT_TECH_PROCESSING_FAILURE',
  
  // External system errors
  PLAN_DOCUMENT_EXT_STORAGE_UNAVAILABLE = 'PLAN_DOCUMENT_EXT_STORAGE_UNAVAILABLE',
  PLAN_DOCUMENT_EXT_OCR_SERVICE_FAILURE = 'PLAN_DOCUMENT_EXT_OCR_SERVICE_FAILURE',
  PLAN_DOCUMENT_EXT_VIRUS_SCAN_FAILURE = 'PLAN_DOCUMENT_EXT_VIRUS_SCAN_FAILURE',
  PLAN_DOCUMENT_EXT_CONVERSION_SERVICE_FAILURE = 'PLAN_DOCUMENT_EXT_CONVERSION_SERVICE_FAILURE'
}

/**
 * Combined error codes for the Plan journey
 * Aggregates all domain-specific error codes for easier import
 */
export const PlanJourneyErrorCodes = {
  ...PlanErrorCodes,
  ...BenefitErrorCodes,
  ...CoverageErrorCodes,
  ...ClaimErrorCodes,
  ...DocumentErrorCodes
};

/**
 * Type representing all possible Plan journey error codes
 */
export type PlanJourneyErrorCode = 
  | PlanErrorCodes
  | BenefitErrorCodes
  | CoverageErrorCodes
  | ClaimErrorCodes
  | DocumentErrorCodes;