/**
 * Error codes constants used throughout the backend services
 * These provide consistent error references for debugging and client error handling
 */

// Authentication error codes
export const AUTH_INVALID_CREDENTIALS = 'AUTH_001';
export const AUTH_TOKEN_EXPIRED = 'AUTH_002'; 
export const AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_003';

// Health journey error codes
export const HEALTH_INVALID_METRIC = 'HEALTH_001';
export const HEALTH_DEVICE_CONNECTION_FAILED = 'HEALTH_002';

// Care journey error codes
export const CARE_PROVIDER_UNAVAILABLE = 'CARE_001';
export const CARE_APPOINTMENT_SLOT_TAKEN = 'CARE_002';
export const CARE_TELEMEDICINE_CONNECTION_FAILED = 'CARE_003';

// Plan journey error codes
export const PLAN_INVALID_CLAIM_DATA = 'PLAN_001';
export const PLAN_COVERAGE_VERIFICATION_FAILED = 'PLAN_002';

// Gamification error codes
export const GAME_INVALID_EVENT_DATA = 'GAME_001';
export const GAME_ACHIEVEMENT_RULE_ERROR = 'GAME_002';

// Notification error codes
export const NOTIFICATION_DELIVERY_FAILED = 'NOTIF_001';
export const NOTIFICATION_TEMPLATE_NOT_FOUND = 'NOTIF_002';
export const NOTIFICATION_PREFERENCE_NOT_FOUND = 'NOTIF_003';
export const NOTIFICATION_PREFERENCE_ALREADY_EXISTS = 'NOTIF_004';
export const NOTIFICATION_PREFERENCE_CREATION_FAILED = 'NOTIF_005';
export const NOTIFICATION_PREFERENCE_UPDATE_FAILED = 'NOTIF_006';
export const NOTIFICATION_PREFERENCE_RETRIEVAL_FAILED = 'NOTIF_007';
export const NOTIFICATION_PREFERENCES_RETRIEVAL_FAILED = 'NOTIF_008';

// API error codes
export const API_RATE_LIMIT_EXCEEDED = 'API_001';
export const API_INVALID_INPUT = 'API_002';

// System error codes
export const SYS_INTERNAL_SERVER_ERROR = 'SYS_001';

// Retry and operation error codes
export const OPERATION_RETRY_SCHEDULED = 'OP_001';
export const OPERATION_RETRY_FAILED = 'OP_002';
export const OPERATION_RETRY_EXHAUSTED = 'OP_003';

// Error code groups for easier reference
export const ERROR_CODES = {
  // Authentication
  AUTH_INVALID_CREDENTIALS,
  AUTH_TOKEN_EXPIRED,
  AUTH_INSUFFICIENT_PERMISSIONS,
  
  // Health journey
  HEALTH_INVALID_METRIC,
  HEALTH_DEVICE_CONNECTION_FAILED,
  
  // Care journey
  CARE_PROVIDER_UNAVAILABLE,
  CARE_APPOINTMENT_SLOT_TAKEN,
  CARE_TELEMEDICINE_CONNECTION_FAILED,
  
  // Plan journey
  PLAN_INVALID_CLAIM_DATA,
  PLAN_COVERAGE_VERIFICATION_FAILED,
  
  // Gamification
  GAME_INVALID_EVENT_DATA,
  GAME_ACHIEVEMENT_RULE_ERROR,
  
  // Notification
  NOTIFICATION_DELIVERY_FAILED,
  NOTIFICATION_TEMPLATE_NOT_FOUND,
  NOTIFICATION_PREFERENCE_NOT_FOUND,
  NOTIFICATION_PREFERENCE_ALREADY_EXISTS,
  NOTIFICATION_PREFERENCE_CREATION_FAILED,
  NOTIFICATION_PREFERENCE_UPDATE_FAILED,
  NOTIFICATION_PREFERENCE_RETRIEVAL_FAILED,
  NOTIFICATION_PREFERENCES_RETRIEVAL_FAILED,
  
  // API
  API_RATE_LIMIT_EXCEEDED,
  API_INVALID_INPUT,
  
  // System
  SYS_INTERNAL_SERVER_ERROR,
  
  // Retry and operations
  OPERATION_RETRY_SCHEDULED,
  OPERATION_RETRY_FAILED,
  OPERATION_RETRY_EXHAUSTED,
};