apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    component: gateway
  annotations:
    kubernetes.io/description: "API Gateway for the AUSTA SuperApp"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: api-gateway
        image: austa-superapp/api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: http
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4000"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3000"
        - name: HEALTH_SERVICE_URL
          value: "http://health-journey:3000"
        - name: CARE_SERVICE_URL
          value: "http://care-journey:3000"
        - name: PLAN_SERVICE_URL
          value: "http://plan-journey:3000"
        - name: GAMIFICATION_SERVICE_URL
          value: "http://gamification-engine:3000"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:3000"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis_url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: jwt_secret
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-secret
              key: sentry_dsn
        - name: DATADOG_API_KEY
          valueFrom:
            secretKeyRef:
              name: datadog-secret
              key: datadog_api_key
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
      - name: regcred
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - api-gateway
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "api-gateway"
        effect: "NoSchedule"