# Prisma Migrate metadata file
# Read more: https://pris.ly/d/prisma-migrate

migration_name = "20230204000000_create_coverage"
provider = "postgresql"
provider_version = "14"

# Migration checksum for integrity verification
checksum = "8a3d6e9f7b2c1d0e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f"

# Migration execution metadata
applied_steps_count = 1
created_at = "2023-02-04T00:00:00.000Z"
finished_at = "2023-02-04T00:00:10.000Z"