apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: plan-journey
  namespace: plan-journey
  labels:
    app: plan-journey
    journey: plan
    part-of: austa-superapp
    managed-by: terraform
    component: journey-service
  annotations:
    description: "Horizontal Pod Autoscaler for Plan Journey service"
    last-updated: "2025-05-19"
    refactoring-note: "Updated as part of AUSTA SuperApp refactoring"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plan-journey
  minReplicas: 3
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 3
          periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 25
          periodSeconds: 60