/**
 * Error codes for the Care journey.
 * 
 * This file defines all error codes used throughout the Care journey, organized by domain
 * (appointment, provider, telemedicine, medication, symptom, treatment) and error type
 * (validation, business, technical, external).
 * 
 * Error codes follow the pattern: CARE_[DOMAIN]_[TYPE]_[SPECIFIC_ERROR]
 * 
 * These codes provide a consistent error identification system that enables precise error
 * tracking, documentation, and localization across the Care journey services.
 */

// ===== APPOINTMENT DOMAIN ERROR CODES =====

/**
 * Validation error codes for the Appointment domain
 */
export const CARE_APPOINTMENT_VALIDATION_INVALID_DATE = 'CARE_APPOINTMENT_VALIDATION_INVALID_DATE';
export const CARE_APPOINTMENT_VALIDATION_INVALID_TIME = 'CARE_APPOINTMENT_VALIDATION_INVALID_TIME';
export const CARE_APPOINTMENT_VALIDATION_INVALID_DURATION = 'CARE_APPOINTMENT_VALIDATION_INVALID_DURATION';
export const CARE_APPOINTMENT_VALIDATION_INVALID_PROVIDER = 'CARE_APPOINTMENT_VALIDATION_INVALID_PROVIDER';
export const CARE_APPOINTMENT_VALIDATION_INVALID_PATIENT = 'CARE_APPOINTMENT_VALIDATION_INVALID_PATIENT';
export const CARE_APPOINTMENT_VALIDATION_INVALID_TYPE = 'CARE_APPOINTMENT_VALIDATION_INVALID_TYPE';
export const CARE_APPOINTMENT_VALIDATION_MISSING_REASON = 'CARE_APPOINTMENT_VALIDATION_MISSING_REASON';

/**
 * Business logic error codes for the Appointment domain
 */
export const CARE_APPOINTMENT_BUSINESS_SLOT_UNAVAILABLE = 'CARE_APPOINTMENT_BUSINESS_SLOT_UNAVAILABLE';
export const CARE_APPOINTMENT_BUSINESS_PROVIDER_UNAVAILABLE = 'CARE_APPOINTMENT_BUSINESS_PROVIDER_UNAVAILABLE';
export const CARE_APPOINTMENT_BUSINESS_DOUBLE_BOOKING = 'CARE_APPOINTMENT_BUSINESS_DOUBLE_BOOKING';
export const CARE_APPOINTMENT_BUSINESS_PAST_DATE = 'CARE_APPOINTMENT_BUSINESS_PAST_DATE';
export const CARE_APPOINTMENT_BUSINESS_TOO_LATE_TO_CANCEL = 'CARE_APPOINTMENT_BUSINESS_TOO_LATE_TO_CANCEL';
export const CARE_APPOINTMENT_BUSINESS_ALREADY_CONFIRMED = 'CARE_APPOINTMENT_BUSINESS_ALREADY_CONFIRMED';
export const CARE_APPOINTMENT_BUSINESS_ALREADY_CANCELLED = 'CARE_APPOINTMENT_BUSINESS_ALREADY_CANCELLED';
export const CARE_APPOINTMENT_BUSINESS_ALREADY_COMPLETED = 'CARE_APPOINTMENT_BUSINESS_ALREADY_COMPLETED';

/**
 * Technical error codes for the Appointment domain
 */
export const CARE_APPOINTMENT_TECHNICAL_CALENDAR_SYNC_FAILED = 'CARE_APPOINTMENT_TECHNICAL_CALENDAR_SYNC_FAILED';
export const CARE_APPOINTMENT_TECHNICAL_NOTIFICATION_FAILED = 'CARE_APPOINTMENT_TECHNICAL_NOTIFICATION_FAILED';
export const CARE_APPOINTMENT_TECHNICAL_SCHEDULING_ENGINE_ERROR = 'CARE_APPOINTMENT_TECHNICAL_SCHEDULING_ENGINE_ERROR';

/**
 * External system error codes for the Appointment domain
 */
export const CARE_APPOINTMENT_EXTERNAL_PROVIDER_SYSTEM_UNAVAILABLE = 'CARE_APPOINTMENT_EXTERNAL_PROVIDER_SYSTEM_UNAVAILABLE';
export const CARE_APPOINTMENT_EXTERNAL_CALENDAR_API_ERROR = 'CARE_APPOINTMENT_EXTERNAL_CALENDAR_API_ERROR';
export const CARE_APPOINTMENT_EXTERNAL_PAYMENT_PROCESSING_ERROR = 'CARE_APPOINTMENT_EXTERNAL_PAYMENT_PROCESSING_ERROR';

// ===== PROVIDER DOMAIN ERROR CODES =====

/**
 * Validation error codes for the Provider domain
 */
export const CARE_PROVIDER_VALIDATION_INVALID_SPECIALTY = 'CARE_PROVIDER_VALIDATION_INVALID_SPECIALTY';
export const CARE_PROVIDER_VALIDATION_INVALID_LICENSE = 'CARE_PROVIDER_VALIDATION_INVALID_LICENSE';
export const CARE_PROVIDER_VALIDATION_INVALID_LOCATION = 'CARE_PROVIDER_VALIDATION_INVALID_LOCATION';
export const CARE_PROVIDER_VALIDATION_INVALID_AVAILABILITY = 'CARE_PROVIDER_VALIDATION_INVALID_AVAILABILITY';
export const CARE_PROVIDER_VALIDATION_INVALID_CONTACT = 'CARE_PROVIDER_VALIDATION_INVALID_CONTACT';

/**
 * Business logic error codes for the Provider domain
 */
export const CARE_PROVIDER_BUSINESS_NOT_FOUND = 'CARE_PROVIDER_BUSINESS_NOT_FOUND';
export const CARE_PROVIDER_BUSINESS_INACTIVE = 'CARE_PROVIDER_BUSINESS_INACTIVE';
export const CARE_PROVIDER_BUSINESS_NOT_ACCEPTING_PATIENTS = 'CARE_PROVIDER_BUSINESS_NOT_ACCEPTING_PATIENTS';
export const CARE_PROVIDER_BUSINESS_SPECIALTY_MISMATCH = 'CARE_PROVIDER_BUSINESS_SPECIALTY_MISMATCH';
export const CARE_PROVIDER_BUSINESS_OUT_OF_NETWORK = 'CARE_PROVIDER_BUSINESS_OUT_OF_NETWORK';

/**
 * Technical error codes for the Provider domain
 */
export const CARE_PROVIDER_TECHNICAL_DIRECTORY_ERROR = 'CARE_PROVIDER_TECHNICAL_DIRECTORY_ERROR';
export const CARE_PROVIDER_TECHNICAL_SEARCH_ENGINE_ERROR = 'CARE_PROVIDER_TECHNICAL_SEARCH_ENGINE_ERROR';
export const CARE_PROVIDER_TECHNICAL_PROFILE_UPDATE_ERROR = 'CARE_PROVIDER_TECHNICAL_PROFILE_UPDATE_ERROR';

/**
 * External system error codes for the Provider domain
 */
export const CARE_PROVIDER_EXTERNAL_DIRECTORY_API_ERROR = 'CARE_PROVIDER_EXTERNAL_DIRECTORY_API_ERROR';
export const CARE_PROVIDER_EXTERNAL_LICENSE_VERIFICATION_ERROR = 'CARE_PROVIDER_EXTERNAL_LICENSE_VERIFICATION_ERROR';
export const CARE_PROVIDER_EXTERNAL_NETWORK_API_ERROR = 'CARE_PROVIDER_EXTERNAL_NETWORK_API_ERROR';

// ===== TELEMEDICINE DOMAIN ERROR CODES =====

/**
 * Validation error codes for the Telemedicine domain
 */
export const CARE_TELEMEDICINE_VALIDATION_INVALID_SESSION = 'CARE_TELEMEDICINE_VALIDATION_INVALID_SESSION';
export const CARE_TELEMEDICINE_VALIDATION_INVALID_PARTICIPANT = 'CARE_TELEMEDICINE_VALIDATION_INVALID_PARTICIPANT';
export const CARE_TELEMEDICINE_VALIDATION_INVALID_MEDIA_TYPE = 'CARE_TELEMEDICINE_VALIDATION_INVALID_MEDIA_TYPE';
export const CARE_TELEMEDICINE_VALIDATION_INVALID_DURATION = 'CARE_TELEMEDICINE_VALIDATION_INVALID_DURATION';

/**
 * Business logic error codes for the Telemedicine domain
 */
export const CARE_TELEMEDICINE_BUSINESS_SESSION_NOT_FOUND = 'CARE_TELEMEDICINE_BUSINESS_SESSION_NOT_FOUND';
export const CARE_TELEMEDICINE_BUSINESS_SESSION_EXPIRED = 'CARE_TELEMEDICINE_BUSINESS_SESSION_EXPIRED';
export const CARE_TELEMEDICINE_BUSINESS_SESSION_ALREADY_STARTED = 'CARE_TELEMEDICINE_BUSINESS_SESSION_ALREADY_STARTED';
export const CARE_TELEMEDICINE_BUSINESS_SESSION_ALREADY_ENDED = 'CARE_TELEMEDICINE_BUSINESS_SESSION_ALREADY_ENDED';
export const CARE_TELEMEDICINE_BUSINESS_PARTICIPANT_NOT_AUTHORIZED = 'CARE_TELEMEDICINE_BUSINESS_PARTICIPANT_NOT_AUTHORIZED';
export const CARE_TELEMEDICINE_BUSINESS_PROVIDER_NOT_AVAILABLE = 'CARE_TELEMEDICINE_BUSINESS_PROVIDER_NOT_AVAILABLE';

/**
 * Technical error codes for the Telemedicine domain
 */
export const CARE_TELEMEDICINE_TECHNICAL_VIDEO_SERVICE_ERROR = 'CARE_TELEMEDICINE_TECHNICAL_VIDEO_SERVICE_ERROR';
export const CARE_TELEMEDICINE_TECHNICAL_AUDIO_SERVICE_ERROR = 'CARE_TELEMEDICINE_TECHNICAL_AUDIO_SERVICE_ERROR';
export const CARE_TELEMEDICINE_TECHNICAL_CONNECTION_ERROR = 'CARE_TELEMEDICINE_TECHNICAL_CONNECTION_ERROR';
export const CARE_TELEMEDICINE_TECHNICAL_RECORDING_ERROR = 'CARE_TELEMEDICINE_TECHNICAL_RECORDING_ERROR';
export const CARE_TELEMEDICINE_TECHNICAL_ENCRYPTION_ERROR = 'CARE_TELEMEDICINE_TECHNICAL_ENCRYPTION_ERROR';

/**
 * External system error codes for the Telemedicine domain
 */
export const CARE_TELEMEDICINE_EXTERNAL_VIDEO_PROVIDER_ERROR = 'CARE_TELEMEDICINE_EXTERNAL_VIDEO_PROVIDER_ERROR';
export const CARE_TELEMEDICINE_EXTERNAL_BANDWIDTH_LIMITATION = 'CARE_TELEMEDICINE_EXTERNAL_BANDWIDTH_LIMITATION';
export const CARE_TELEMEDICINE_EXTERNAL_MEDIA_SERVER_ERROR = 'CARE_TELEMEDICINE_EXTERNAL_MEDIA_SERVER_ERROR';

// ===== MEDICATION DOMAIN ERROR CODES =====

/**
 * Validation error codes for the Medication domain
 */
export const CARE_MEDICATION_VALIDATION_INVALID_NAME = 'CARE_MEDICATION_VALIDATION_INVALID_NAME';
export const CARE_MEDICATION_VALIDATION_INVALID_DOSAGE = 'CARE_MEDICATION_VALIDATION_INVALID_DOSAGE';
export const CARE_MEDICATION_VALIDATION_INVALID_FREQUENCY = 'CARE_MEDICATION_VALIDATION_INVALID_FREQUENCY';
export const CARE_MEDICATION_VALIDATION_INVALID_DURATION = 'CARE_MEDICATION_VALIDATION_INVALID_DURATION';
export const CARE_MEDICATION_VALIDATION_INVALID_PRESCRIPTION = 'CARE_MEDICATION_VALIDATION_INVALID_PRESCRIPTION';
export const CARE_MEDICATION_VALIDATION_INVALID_REFILL = 'CARE_MEDICATION_VALIDATION_INVALID_REFILL';

/**
 * Business logic error codes for the Medication domain
 */
export const CARE_MEDICATION_BUSINESS_NOT_FOUND = 'CARE_MEDICATION_BUSINESS_NOT_FOUND';
export const CARE_MEDICATION_BUSINESS_INTERACTION_DETECTED = 'CARE_MEDICATION_BUSINESS_INTERACTION_DETECTED';
export const CARE_MEDICATION_BUSINESS_ALLERGY_DETECTED = 'CARE_MEDICATION_BUSINESS_ALLERGY_DETECTED';
export const CARE_MEDICATION_BUSINESS_CONTRAINDICATION_DETECTED = 'CARE_MEDICATION_BUSINESS_CONTRAINDICATION_DETECTED';
export const CARE_MEDICATION_BUSINESS_PRESCRIPTION_EXPIRED = 'CARE_MEDICATION_BUSINESS_PRESCRIPTION_EXPIRED';
export const CARE_MEDICATION_BUSINESS_NO_REFILLS_REMAINING = 'CARE_MEDICATION_BUSINESS_NO_REFILLS_REMAINING';
export const CARE_MEDICATION_BUSINESS_DUPLICATE_MEDICATION = 'CARE_MEDICATION_BUSINESS_DUPLICATE_MEDICATION';

/**
 * Technical error codes for the Medication domain
 */
export const CARE_MEDICATION_TECHNICAL_DATABASE_ERROR = 'CARE_MEDICATION_TECHNICAL_DATABASE_ERROR';
export const CARE_MEDICATION_TECHNICAL_REMINDER_SYSTEM_ERROR = 'CARE_MEDICATION_TECHNICAL_REMINDER_SYSTEM_ERROR';
export const CARE_MEDICATION_TECHNICAL_INTERACTION_CHECK_ERROR = 'CARE_MEDICATION_TECHNICAL_INTERACTION_CHECK_ERROR';

/**
 * External system error codes for the Medication domain
 */
export const CARE_MEDICATION_EXTERNAL_PHARMACY_API_ERROR = 'CARE_MEDICATION_EXTERNAL_PHARMACY_API_ERROR';
export const CARE_MEDICATION_EXTERNAL_PRESCRIPTION_SERVICE_ERROR = 'CARE_MEDICATION_EXTERNAL_PRESCRIPTION_SERVICE_ERROR';
export const CARE_MEDICATION_EXTERNAL_DRUG_DATABASE_ERROR = 'CARE_MEDICATION_EXTERNAL_DRUG_DATABASE_ERROR';

// ===== SYMPTOM DOMAIN ERROR CODES =====

/**
 * Validation error codes for the Symptom domain
 */
export const CARE_SYMPTOM_VALIDATION_INVALID_DESCRIPTION = 'CARE_SYMPTOM_VALIDATION_INVALID_DESCRIPTION';
export const CARE_SYMPTOM_VALIDATION_INVALID_SEVERITY = 'CARE_SYMPTOM_VALIDATION_INVALID_SEVERITY';
export const CARE_SYMPTOM_VALIDATION_INVALID_DURATION = 'CARE_SYMPTOM_VALIDATION_INVALID_DURATION';
export const CARE_SYMPTOM_VALIDATION_INVALID_FREQUENCY = 'CARE_SYMPTOM_VALIDATION_INVALID_FREQUENCY';
export const CARE_SYMPTOM_VALIDATION_INVALID_BODY_LOCATION = 'CARE_SYMPTOM_VALIDATION_INVALID_BODY_LOCATION';

/**
 * Business logic error codes for the Symptom domain
 */
export const CARE_SYMPTOM_BUSINESS_NOT_FOUND = 'CARE_SYMPTOM_BUSINESS_NOT_FOUND';
export const CARE_SYMPTOM_BUSINESS_EMERGENCY_DETECTED = 'CARE_SYMPTOM_BUSINESS_EMERGENCY_DETECTED';
export const CARE_SYMPTOM_BUSINESS_REQUIRES_IMMEDIATE_CARE = 'CARE_SYMPTOM_BUSINESS_REQUIRES_IMMEDIATE_CARE';
export const CARE_SYMPTOM_BUSINESS_CONFLICTING_SYMPTOMS = 'CARE_SYMPTOM_BUSINESS_CONFLICTING_SYMPTOMS';

/**
 * Technical error codes for the Symptom domain
 */
export const CARE_SYMPTOM_TECHNICAL_CHECKER_ENGINE_ERROR = 'CARE_SYMPTOM_TECHNICAL_CHECKER_ENGINE_ERROR';
export const CARE_SYMPTOM_TECHNICAL_ANALYSIS_ERROR = 'CARE_SYMPTOM_TECHNICAL_ANALYSIS_ERROR';
export const CARE_SYMPTOM_TECHNICAL_TRACKING_ERROR = 'CARE_SYMPTOM_TECHNICAL_TRACKING_ERROR';

/**
 * External system error codes for the Symptom domain
 */
export const CARE_SYMPTOM_EXTERNAL_MEDICAL_DATABASE_ERROR = 'CARE_SYMPTOM_EXTERNAL_MEDICAL_DATABASE_ERROR';
export const CARE_SYMPTOM_EXTERNAL_DIAGNOSTIC_API_ERROR = 'CARE_SYMPTOM_EXTERNAL_DIAGNOSTIC_API_ERROR';

// ===== TREATMENT DOMAIN ERROR CODES =====

/**
 * Validation error codes for the Treatment domain
 */
export const CARE_TREATMENT_VALIDATION_INVALID_TYPE = 'CARE_TREATMENT_VALIDATION_INVALID_TYPE';
export const CARE_TREATMENT_VALIDATION_INVALID_PROTOCOL = 'CARE_TREATMENT_VALIDATION_INVALID_PROTOCOL';
export const CARE_TREATMENT_VALIDATION_INVALID_DURATION = 'CARE_TREATMENT_VALIDATION_INVALID_DURATION';
export const CARE_TREATMENT_VALIDATION_INVALID_FREQUENCY = 'CARE_TREATMENT_VALIDATION_INVALID_FREQUENCY';
export const CARE_TREATMENT_VALIDATION_INVALID_PROVIDER = 'CARE_TREATMENT_VALIDATION_INVALID_PROVIDER';

/**
 * Business logic error codes for the Treatment domain
 */
export const CARE_TREATMENT_BUSINESS_NOT_FOUND = 'CARE_TREATMENT_BUSINESS_NOT_FOUND';
export const CARE_TREATMENT_BUSINESS_CONTRAINDICATION_DETECTED = 'CARE_TREATMENT_BUSINESS_CONTRAINDICATION_DETECTED';
export const CARE_TREATMENT_BUSINESS_ALREADY_IN_PROGRESS = 'CARE_TREATMENT_BUSINESS_ALREADY_IN_PROGRESS';
export const CARE_TREATMENT_BUSINESS_REQUIRES_PRIOR_AUTHORIZATION = 'CARE_TREATMENT_BUSINESS_REQUIRES_PRIOR_AUTHORIZATION';
export const CARE_TREATMENT_BUSINESS_NOT_COVERED = 'CARE_TREATMENT_BUSINESS_NOT_COVERED';

/**
 * Technical error codes for the Treatment domain
 */
export const CARE_TREATMENT_TECHNICAL_PLAN_GENERATION_ERROR = 'CARE_TREATMENT_TECHNICAL_PLAN_GENERATION_ERROR';
export const CARE_TREATMENT_TECHNICAL_PROGRESS_TRACKING_ERROR = 'CARE_TREATMENT_TECHNICAL_PROGRESS_TRACKING_ERROR';
export const CARE_TREATMENT_TECHNICAL_OUTCOME_ANALYSIS_ERROR = 'CARE_TREATMENT_TECHNICAL_OUTCOME_ANALYSIS_ERROR';

/**
 * External system error codes for the Treatment domain
 */
export const CARE_TREATMENT_EXTERNAL_PROTOCOL_DATABASE_ERROR = 'CARE_TREATMENT_EXTERNAL_PROTOCOL_DATABASE_ERROR';
export const CARE_TREATMENT_EXTERNAL_AUTHORIZATION_SERVICE_ERROR = 'CARE_TREATMENT_EXTERNAL_AUTHORIZATION_SERVICE_ERROR';
export const CARE_TREATMENT_EXTERNAL_COVERAGE_API_ERROR = 'CARE_TREATMENT_EXTERNAL_COVERAGE_API_ERROR';