apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: care-service
  namespace: care-journey
  labels:
    app: care-service
    journey: care
    part-of: austa-superapp
    managed-by: terraform
  annotations:
    description: "Horizontal Pod Autoscaler for Care Journey service"
    last-updated: "2023-04-15"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: care-service
  minReplicas: 5
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "1000"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60