nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org/"

# Workspace configuration for monorepo structure
workspaces:
  packages:
    - "design-system"
    - "primitives"
    - "interfaces"
    - "journey-context"
    - "shared"
    - "mobile"
    - "web"
    - "types"

# Resolve version conflicts identified in the specification
resolutions:
  minimatch: "5.1.6"
  semver: "7.5.4"
  ws: "8.16.0"
  "react-native": "0.73.4"
  "@tanstack/react-query": "5.25.0"
  "typescript": "5.3.3"

# Configure proper peer dependency handling
packageExtensions:
  "@testing-library/jest-native@*":
    peerDependencies:
      "react-test-renderer": "18.2.0"
  "react-test-renderer@*":
    peerDependencies:
      "react": "18.2.0"
  "react-native@*":
    peerDependencies:
      "react": "18.2.0"
  "@react-native-community/cli@*":
    peerDependencies:
      "react-native": "0.73.4"
  "react-native-reanimated@*":
    peerDependencies:
      "react-native": "0.73.4"
      "react": "18.2.0"
  "react-native-gesture-handler@*":
    peerDependencies:
      "react-native": "0.73.4"
      "react": "18.2.0"
  "react-native-svg@*":
    peerDependencies:
      "react-native": "0.73.4"
      "react": "18.2.0"
  "@babel/plugin-transform-*@*":
    peerDependencies:
      "@babel/core": "^7.0.0"

# Update plugin configuration for workspace tools
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

# Enable consistent versioning across packages
version: 1.0.0

# Enable TypeScript project references for proper build order
enableGlobalCache: true
nmMode: hardlinks-local

# Configure proper hoisting of dependencies
nmHoistingLimits: workspaces