name: Auto Commit and Push

on:
  # Manual trigger from Actions tab
  workflow_dispatch:
  
  # Optional: You can also schedule this to run periodically
  # schedule:
  #   - cron: '0 0 * * *'  # Runs at midnight UTC every day

jobs:
  commit-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch all history for all tags and branches
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Check for changes
        id: git-check
        run: |
          git status --porcelain
          echo "has_changes=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)" >> $GITHUB_OUTPUT
      
      - name: Stage all changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: git add .
        continue-on-error: false
      
      - name: Commit changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git commit -m "Auto-commit: Sync package structure changes [skip ci]" -m "Automated commit via GitHub Actions workflow to maintain synchronized state across the monorepo structure"
        continue-on-error: false
      
      - name: Push changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git push origin ${GITHUB_REF#refs/heads/}
        continue-on-error: false